apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-nodejs-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nodejs-app
  template:
    metadata:
      labels:
        app: demo-nodejs-app
    spec:
      volumes:
      - name: demo-nodejs-storage
        persistentVolumeClaim:
          claimName: demo-nodejs-pvc
      containers:
      - name: demo-nodejs-app
        image: chungnd/nodejs-mongodb:latest
        volumeMounts:
          - name: demo-nodejs-storage
            mountPath: /app/public/images       
        ports:
        - containerPort: 3000
        envFrom:
# Khai báo các biến cấu hình        
          - configMapRef:
              name: demo-nodejs-configmap
# Khai báo mật khẩu db mongo, redis
          - secretRef:
              name: demo-db-secret
          - secretRef:
              name: demo-redis-secret
        # env:
        #   - name: DB_HOST
        #     value: demo-mongodb-service
        #   - name: DB_PORT
        #     value: "27017"
        #   - name: DB_NAME
        #     value: my_db
        #   - name: REDIS_HOST
        #     value: demo-redis-service
        #   - name: REDIS_PORT
        #     value: "6379"
        #   - name: PORT
        #     value: "3000"
        # env:
        #   - name: DB_ROOT_USER
        #     valueFrom:
        #       secretKeyRef:
        #         name: mongodb-secret
        #         key: mongo-root-username

        #   - name: DB_ROOT_PASS
        #     valueFrom:
        #       secretKeyRef:
        #         name: mongodb-secret
        #         key: mongo-root-password                
        
   
              