apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-ingress-service
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #cert-manager.io/cluster-issuer: "wildcard-cluster-issuer"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx     
spec:
  rules:

  - host: monitor.motthang.ga
    http:
      paths:
      - backend:
          service:
            name: grafana-service-extenal
            port:
              number: 80
        path: /
        pathType: Prefix

 